# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
permalink: /blog/:year/:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3001
safe: true

# edit here to achieve your personal greatness
url: http://www.facundo.io
baseurl: /
title: Facundo Carreiro
author: Facundo Carreiro
description: Personal blog and resume
avatar: profile.jpg
email: contact@fa&#99;un&#37;6&#52;&#111;&#46;io
github: fcarreiro
twitter: ko9labs
linkedin: fcarreiro
# stackoverflow: username   # e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
disqus: fcmod
google_analytics: UA-31714232-1
