# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3001
safe: true

# edit here to achieve your personal greatness
url: http://www.facundo.io
# baseurl: http://www.facundo.io
title: Facundo Carreiro
author: Facundo Carreiro
description: Personal blog and resume
avatar: profile.jpg
email: contact@fa&#99;un&#37;6&#52;&#111;&#46;io
github: fcarreiro # username
twitter: ko9labs
# linkedin: username
# stackoverflow: username   # e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
disqus: fcmod
google_analytics: UA-31714232-1
